Mensaje:  error al registrar un log An exception occurred while initializing the database. See the InnerException for details.
HelpLink: 
Hresult: -2146233087
Innerexception: System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en System.Data.Entity.Migrations.DbMigrator.SeedDatabase()
   en System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   en System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   en System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   en System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   en System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   en System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   en System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   en System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
Source: EntityFramework
StackTrace:    en System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   en System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   en System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   en System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   en System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   en System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   en System.Data.Entity.DbSet`1.Add(TEntity entity)
   en Emsys.Logs.Log.AgregarLogError(String IdUsuario, String terminal, String modulo, String Entidad, Int32 idEntidad, String accion, String detalles, Int32 codigo) en C:\Users\Andres\Desktop\PIs_repo\Emsys.Logs\Log.cs:l√≠nea 78
TargetSite: Void PerformInitializationAction(System.Action)
